version: '3'
services:
        postgres:
                image: 'postgres:latest'
                environment:
                        - POSTGRES_PASSWORD=postgers_password
        redis: 
                image: 'redis:latest'
        nginx:
                restart: always
                build:
                        dockerfile: Dockerfile.dev
                        context: ./nginx
                ports:
                        - '3050:80'
        api:
                build:   
                        dockerfile: Dockerfile.dev #only the name of the file
                        context: ./server #source code -> where to look for the dockerfile
                volumes:
                        - /app/node_modules
                        - ./server:/app
                environment:
                        - REDIS_HOST=redis
                        - REDIS_PORT=6379
                        - PGUSER=postgres
                        - PGHOST=postgres #the service that we made above)
                        - PGDATABASE=postgres
                        - PGPASSWORD=postgres_password
                        - PGPORT=5432
        client:
                build:
                        dockerfile: Dockerfile.dev
                        context: ./client
                volumes:
                        - /app/node_modules
                        - ./client:/app
        worker:
                build:
                        dockerfile: Dockerfile.dev
                        context: ./worker
                volumes:
                        - /app/node_modules
                        - ./worker:/app
                environment:
                        - REDIS_HOST=redis
                        - REDIS_PORT=6379
